### ISSUE TITLE
When using filter "rasp" on my work machine, the application crashes

### ISSUE THREAD

**Issue by jwalthour** [jwalthour/passiveAgressor#21]
Windows 10

**Comment by jdw-creare** [comment]
````
Exception in thread "main" java.lang.NullPointerException
        at passiveAggressor.PassiveAggressor$1.nextPacket(PassiveAggressor.java:246)
        at passiveAggressor.PassiveAggressor$1.nextPacket(PassiveAggressor.java:1)
        at org.jnetpcap.Pcap.loop(Native Method)
        at org.jnetpcap.Pcap.loop(Unknown Source)
        at passiveAggressor.PassiveAggressor.listen(PassiveAggressor.java:275)
        at passiveAggressor.PassiveAggressor.main(PassiveAggressor.java:102)
````

**Comment by jdw-creare** [comment]
Also, listing without `-m` includes a line reading:
````
10:65:30:27:69:CE       10.11.35.1      null
````

**Comment by jwalthour** [comment]
OBE in switch to C#
